# Disabling sudo moves build to the Container Based Infrastructure on Travis CI
sudo: false

language: android
jdk: oraclejdk8

before_install:
  - pip install --user codecov
  - echo $ANDROID_HOME
  - mkdir -p /usr/local/android-sdk/licenses
  - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > /usr/local/android-sdk/licenses/android-sdk-license
  - echo "84831b9409646a918e30573bab4c9c91346d8abd" > /usr/local/android-sdk/licenses/android-sdk-preview-license

android:
  components:
    - android-25
    - platform-tools
    - tools
    - build-tools-25.0.2
    - extra-android-m2repository
    - extra-android-support

script:
  - sh ci.sh
  
after_success:
  - codecov

notifications:
  email:
    recipients:
      - artem.zinnatullin@gmail.com
      - nikitin.da.90@gmail.com
    on_success: never
    on_failure: always

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
