# We need sudo to install additional packages.
sudo: required

language: java
jdk: oraclejdk8

before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y curl unzip
  - pip install --user codecov
  - export ANDROID_HOME="$HOME"/android-sdk
  - mkdir -p "$ANDROID_HOME"
  - export ANDROID_SDK_FILE_NAME=sdk-tools-darwin-3859397.zip
  - curl --fail https://dl.google.com/android/repository/$ANDROID_SDK_FILE_NAME --silent --location --output $ANDROID_SDK_FILE_NAME
  - unzip -qq $ANDROID_SDK_FILE_NAME -d "$ANDROID_HOME"
  - rm $ANDROID_SDK_FILE_NAME
  - export ANDROID_SDK_INSTALL_COMPONENT="echo \"y\" | \"$ANDROID_HOME\"/tools/bin/sdkmanager > /dev/null"
  - eval $ANDROID_SDK_INSTALL_COMPONENT '"tools"'
  - eval $ANDROID_SDK_INSTALL_COMPONENT '"platform-tools"'
  - eval $ANDROID_SDK_INSTALL_COMPONENT '"build-tools;25.0.2"'
  - eval $ANDROID_SDK_INSTALL_COMPONENT '"platforms;android-25"'
  - eval $ANDROID_SDK_INSTALL_COMPONENT '"extras;android;m2repository"'
  - eval $ANDROID_SDK_INSTALL_COMPONENT '"extras;google;m2repository"'

script:
  - ./ci.sh
  
after_success:
  - codecov

deploy:
  - provider: script
    script: PUBLISH_RELEASE=true ./ci.sh
    skip_cleanup: true
    on:
      tags: true

notifications:
  email:
    recipients:
      - artem.zinnatullin@gmail.com
      - nikitin.da.90@gmail.com
    on_success: never
    on_failure: always

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
